# ---------------------- #
# site config            #
# ---------------------- #
name: Perry Yeh
baseurl:
url: https://yeh.sh
keywords: Perry Yeh
description: A software engineer.

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
rouge: true
markdown: kramdown
timezone: America/Los_Angeles

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

